# Ativa o profile de Stubs para testes
spring:
  profiles:
    active: stub # Ativa o perfil "stub" por padrão

server:
  port: 8080

broker:
  routes:
    - id: "consulta-cpf-lote-v1"
      path: "/api-cpf/consulta"
      method: "POST"
      api: "cpf-light-api"
  
  apis:
    "cpf-light-api":
      target-url: "https://h-apigateway.conectagov.np.estaleiro.serpro.gov.br/api-cpf-light/v2/consulta/cpf"
      token-url: "https://h-apigateway.conectagov.np.estaleiro.serpro.gov.br/oauth2/jwt-token"

  clients:
    # "chave segura" (apelido) 
    sad-portal-cidadao:
      # O valor real do header vai em um campo próprio
      xRoadId: "SAD/PORTAL_CIDADAO"
      clientId: "******"
      clientSecret: "******"
